### ISSUE TITLE
Add MAP covariates

### ISSUE THREAD

**Issue by goldingn** [idem-lab/map-ir-pipeline#78]
Separate to wanting to reproduce Hancock et al.'s results with those sources, we should first get this running in a reasonable set of MAP's covariates. As a priority we should include:

- MAP's annual ITN and IRS coverage estimates
- MAP's suite of annual climatic variables
- MAP's population density, elevation layers, etc.

Based on the top performers here: https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000633#sec021 and details and sources here: #42 , we also should get crop types/yields (e.g. from SPAM).

Most of these, we have already accessed for IR mapping and vector distribution modelling. @geryan can you help here?

**Comment by geryan** [comment]
Argh sorry I just saw this msg - absolutely - will put you together a stack

**Comment by njtierney** [comment]
resolved in #83
